### ISSUE TITLE
No message preview

### ISSUE THREAD

**Issue by rogalian** [m-ober/phpbb-discord-notifications#13]
Got the webhook all running, however I don't get any message preview in Discord
![image](https://github.com/m-ober/phpbb-discord-notifications/assets/5140184/099dcb9f-6f5a-4415-8f25-5faaac61b77d)

![image](https://github.com/m-ober/phpbb-discord-notifications/assets/5140184/85779034-c4aa-4b4c-8209-356c06ec6e8d)

Is there possibly a permission required within phpBB for the extension to be able to read the message?

**Comment by m-ober** [comment]
Do you have this option enabled in your Discord client?

![image](https://github.com/m-ober/phpbb-discord-notifications/assets/11992838/6a8a247d-df75-4e74-979f-1e07a6b45b6e)

**Comment by rogalian** [comment]
Ah, crumbs, that's very deliberately off as it's horrendous. Thank you, I might look into eliminating that requirement in future.
