### ISSUE TITLE
Webhook error sending test messages.

### ISSUE THREAD

**Issue by ajam123** [m-ober/phpbb-discord-notifications#5]
```
Information
There was a problem with sending the test message. Check your webhook URL and verify your server meets the extension requirements
```

I'm using the exactly version you used for the testing version which is 3.3.5

Webhook is correct and copied directly from Discord itself.

**Comment by m-ober** [comment]
Can you maybe make a screenshot of your configuration? Don't forget to redact private information (for example the part after `https://discord.com/api/webhooks/...`).

If you have access to your server logs, also see if there is anything regarding this error.

**Comment by rogalian** [comment]
I get this in the logs:

[Fri May 12 11:05:34.405489 2023] [php7:error] [pid 1113761] [client 94.196.76.185:47966] PHP Fatal error:  Uncaught Error: Call to undefined function mober\\discordnotifications\\curl_init() in /srv/phpBB3/ext/mober/discordnotifications/notification_service.php:360\nStack trace:\n#0 /srv/phpBB3/ext/mober/discordnotifications/notification_service.php(271): mober\\discordnotifications\\notification_service->execute_discord_webhook()\n#1 /srv/phpBB3/ext/mober/discordnotifications/acp/discord_notifications_module.php(178): mober\\discordnotifications\\notification_service->force_send_discord_notification()\n#2 /srv/phpBB3/ext/mober/discordnotifications/acp/discord_notifications_module.php(87): mober\\discordnotifications\\acp\\discord_notifications_module->process_send_test_message()\n#3 /srv/phpBB3/includes/functions_module.php(676): mober\\discordnotifications\\acp\\discord_notifications_module->main()\n#4 /srv/phpBB3/adm/index.php(81): p_master->load_active()\n#5 {main}\n  thrown in /srv/phpBB3/ext/mober/discordnotifications/notification_service.php on line 360, referer: https://forum.arcadeotaku.com/adm/index.php?i=-mober-discordnotifications-acp-discord_notifications_module&sid=d84fbc737cf2f00cfd4332a443890633&mode=settings

**Comment by m-ober** [comment]
It looks like your PHP installation is missing the `curl` extension. Can you check if you have it installed?

**Comment by rogalian** [comment]
Ah, thank you. php7.4-curl now installed. Notification is working but no preview is attached, if I can't figure it out I'll raise another issue :)
